export type SearchIntent = 'informacional' | 'comercial' | 'transacional' | 'navegacional';

export interface KeywordMapEntry {
	primaryKeyword: string;
	secondaryKeywords: readonly string[];
	intent: SearchIntent;
	title: string;
	description: string;
	heading?: string;
}

export const keywordMap = {
	'/': {
		primaryKeyword: 'consultoria em segurança do trabalho',
		secondaryKeywords: ['saúde ocupacional', 'laudos técnicos', 'eSocial', 'projetos de engenharia'],
		intent: 'comercial',
		title: 'Consultoria em segurança do trabalho e engenharia | AJN',
		description: 'Consultoria em segurança do trabalho e engenharia para empresas. Conheça os serviços da AJN em laudos, eSocial e projetos técnicos.',
	},
	'/sobre-nos': {
		primaryKeyword: 'AJN Consultoria e Engenharia',
		secondaryKeywords: ['segurança do trabalho', 'saúde ocupacional', 'engenharia', 'QSSMA'],
		intent: 'navegacional',
		title: 'Sobre a AJN: consultoria em segurança do trabalho e engenharia',
		description: 'Conheça a AJN Consultoria e Engenharia, sua atuação em segurança do trabalho, saúde ocupacional, QSSMA, laudos e projetos técnicos.',
	},
	'/servicos': {
		primaryKeyword: 'serviços de segurança do trabalho',
		secondaryKeywords: ['saúde ocupacional', 'projetos de engenharia', 'prevenção de riscos', 'treinamentos de NRs'],
		intent: 'comercial',
		title: 'Serviços de segurança do trabalho e engenharia | AJN',
		description: 'Veja os serviços da AJN em segurança do trabalho, saúde ocupacional, meio ambiente, projetos de engenharia, prevenção contra incêndio e treinamentos.',
	},
	'/contato': {
		primaryKeyword: 'contato consultoria em segurança do trabalho',
		secondaryKeywords: ['orçamento de serviços de engenharia', 'atendimento AJN', 'Belo Horizonte'],
		intent: 'transacional',
		title: 'Contato e orçamento | AJN Consultoria e Engenharia',
		description: 'Fale com a AJN Consultoria e Engenharia para explicar sua demanda, solicitar orientação técnica ou pedir um orçamento em segurança do trabalho e engenharia.',
	},
	'/elaboracao-pgr': {
		primaryKeyword: 'elaboração de PGR',
		secondaryKeywords: ['gerenciamento de riscos ocupacionais', 'inventário de riscos', 'plano de ação'],
		intent: 'comercial',
		title: 'Elaboração de PGR e gestão de riscos ocupacionais | AJN',
		description: 'Elaboração de PGR com inventário de riscos ocupacionais e plano de ação conforme a NR-1. Entenda o escopo e solicite uma avaliação da AJN.',
	},
	'/emissao-ltcat': {
		primaryKeyword: 'emissão de LTCAT',
		secondaryKeywords: ['avaliação previdenciária', 'agentes de exposição', 'responsabilidade técnica'],
		intent: 'comercial',
		title: 'Emissão de LTCAT | AJN Consultoria e Engenharia',
		description: 'Entenda o que o LTCAT avalia, quem pode assiná-lo e quais informações sua empresa deve reunir. Solicite uma avaliação de escopo à AJN.',
	},
	'/blog': {
		primaryKeyword: 'blog de segurança do trabalho',
		secondaryKeywords: ['saúde ocupacional', 'PGR', 'PCMSO', 'LTCAT', 'gestão de riscos'],
		intent: 'informacional',
		title: 'Blog de segurança do trabalho e engenharia | AJN',
		description: 'Artigos da AJN sobre segurança do trabalho, PGR, PCMSO, LTCAT, saúde ocupacional, gestão de riscos e engenharia.',
	},
	'/mapa-site': {
		primaryKeyword: 'mapa do site AJN',
		secondaryKeywords: ['serviços de engenharia', 'artigos de segurança do trabalho'],
		intent: 'navegacional',
		title: 'Mapa do site | AJN Consultoria e Engenharia',
		description: 'Encontre serviços, páginas institucionais e artigos da AJN Consultoria e Engenharia organizados por assunto.',
	},
	'/servicos/assessoria-e-consultoria-em-saude-ocupacional': {
		primaryKeyword: 'assessoria em saúde ocupacional',
		secondaryKeywords: ['consultoria em saúde ocupacional', 'riscos ocupacionais', 'programas de prevenção'],
		intent: 'comercial',
		title: 'Assessoria em saúde ocupacional | AJN Consultoria e Engenharia',
		description: 'Assessoria em saúde ocupacional para identificar riscos, apoiar programas de prevenção e orientar medidas de controle no ambiente de trabalho.',
	},
	'/servicos/gestao-ambiental': {
		primaryKeyword: 'gestão ambiental empresarial',
		secondaryKeywords: ['gestão de resíduos', 'segregação de resíduos', 'treinamento ambiental'],
		intent: 'comercial',
		title: 'Gestão ambiental e de resíduos | AJN Consultoria e Engenharia',
		description: 'Gestão ambiental para empresas, com orientação sobre segregação, armazenamento, destinação de resíduos e conscientização das equipes.',
	},
	'/servicos/gestao-da-qualidade': {
		primaryKeyword: 'gestão da qualidade em obras',
		secondaryKeywords: ['plano de qualidade', 'ficha de verificação de serviços', 'acompanhamento de obra'],
		intent: 'comercial',
		title: 'Gestão da qualidade em obras | AJN Consultoria e Engenharia',
		description: 'Gestão da qualidade em obras com plano de qualidade, fichas de verificação, controle de materiais e acompanhamento técnico no local.',
	},
	'/servicos/gestao-do-e-social': {
		primaryKeyword: 'gestão do eSocial',
		secondaryKeywords: ['eventos S-2220 e S-2240', 'registros de SST', 'saúde e segurança do trabalho'],
		intent: 'comercial',
		title: 'Gestão do eSocial para empresas | AJN Consultoria e Engenharia',
		description: 'Gestão do eSocial para organizar informações de saúde e segurança do trabalho e apoiar o envio dos eventos S-2220 e S-2240.',
	},
	'/servicos/pcmso-e-asos': {
		primaryKeyword: 'PCMSO e ASO',
		secondaryKeywords: ['saúde ocupacional', 'exames ocupacionais', 'gestão de ASOs'],
		intent: 'comercial',
		title: 'PCMSO e ASO: gestão da saúde ocupacional | AJN',
		description: 'Gestão de PCMSO e ASOs alinhada aos riscos ocupacionais, com acompanhamento de exames, documentos e retornos ao trabalho.',
	},
	'/servicos/pericias-em-periculosidade-e-insalubridade': {
		primaryKeyword: 'perícia de insalubridade e periculosidade',
		secondaryKeywords: ['laudo técnico', 'agentes nocivos', 'riscos ocupacionais'],
		intent: 'comercial',
		title: 'Perícia de insalubridade e periculosidade | AJN',
		description: 'Perícias de insalubridade e periculosidade para avaliar exposições, situações de risco e condições de trabalho com fundamentação técnica.',
	},
	'/servicos/projetos-de-combate-a-incendio-e-panico-ppcip': {
		primaryKeyword: 'projeto de prevenção e combate a incêndio',
		secondaryKeywords: ['PPCIP', 'AVCB', 'CLCB', 'segurança contra incêndio'],
		intent: 'comercial',
		title: 'Projeto de prevenção e combate a incêndio | AJN',
		description: 'Projetos de prevenção e combate a incêndio para edificações, com orientação sobre PPCIP, regularização e renovação de AVCB ou CLCB.',
	},
	'/servicos/regularizacao-de-imoveis-junto-ao-corpo-de-bombeiros': {
		primaryKeyword: 'regularização de imóveis junto ao Corpo de Bombeiros',
		secondaryKeywords: ['AVCB', 'CLCB', 'projeto contra incêndio', 'adequação de imóveis'],
		intent: 'transacional',
		title: 'Regularização de imóveis junto ao Corpo de Bombeiros | AJN',
		description: 'Regularização de imóveis junto ao Corpo de Bombeiros, com projetos, análise de conformidade, documentação e acompanhamento técnico.',
	},
	'/servicos/treinamento-de-nrs': {
		primaryKeyword: 'treinamento de NRs',
		secondaryKeywords: ['capacitação em segurança do trabalho', 'NR-1', 'NR-6', 'NR-10', 'NR-35'],
		intent: 'comercial',
		title: 'Treinamento de NRs e segurança do trabalho | AJN',
		description: 'Treinamentos de Normas Regulamentadoras para apoiar a capacitação das equipes em segurança, saúde ocupacional e prevenção de riscos.',
	},
	'/servicos/projetos-eletricos-residenciais-comerciais-e-prediais-com-foco-em-qualidade-prazo-e-economia': {
		primaryKeyword: 'projeto elétrico residencial, comercial e predial',
		secondaryKeywords: ['instalações elétricas', 'engenharia elétrica', 'eficiência energética'],
		intent: 'comercial',
		title: 'Projetos elétricos residenciais, comerciais e prediais | AJN',
		description: 'Projetos elétricos residenciais, comerciais e prediais com planejamento técnico, segurança, eficiência e atenção ao escopo da obra.',
	},
	'/empresa-que-elabora-pgr': {
		primaryKeyword: 'consultoria para PGR',
		secondaryKeywords: ['gerenciamento de riscos ocupacionais', 'programa de gerenciamento de riscos'],
		intent: 'comercial',
		title: 'Consultoria para PGR e gerenciamento de riscos | AJN',
		description: 'Consultoria para estruturar o PGR, avaliar riscos ocupacionais e organizar medidas de prevenção de acordo com a realidade da empresa.',
		heading: 'Consultoria para PGR e gerenciamento de riscos',
	},
	'/empresa-que-faz-pgr': {
		primaryKeyword: 'elaboração de PGR para empresas',
		secondaryKeywords: ['PGR', 'inventário de riscos', 'plano de ação'],
		intent: 'transacional',
		title: 'Elaboração de PGR para empresas | AJN Consultoria e Engenharia',
		description: 'Elaboração de PGR para empresas, com inventário de riscos, plano de ação e documentação ajustada às atividades e exposições identificadas.',
		heading: 'Elaboração de PGR para empresas',
	},
	'/instalacoes-eletricas-projeto': {
		primaryKeyword: 'planejamento de instalações elétricas',
		secondaryKeywords: ['engenharia elétrica', 'distribuição de energia', 'segurança elétrica'],
		intent: 'informacional',
		title: 'Planejamento de instalações elétricas | AJN',
		description: 'Entenda o planejamento de instalações elétricas e os elementos técnicos necessários para distribuir energia com segurança e eficiência.',
		heading: 'Planejamento de instalações elétricas',
	},
	'/projeto-instalacoes-eletricas': {
		primaryKeyword: 'projeto de instalações elétricas para obras',
		secondaryKeywords: ['projeto elétrico', 'instalações prediais', 'conformidade técnica'],
		intent: 'comercial',
		title: 'Projeto de instalações elétricas para obras | AJN',
		description: 'Projeto de instalações elétricas para obras residenciais, comerciais e prediais, com definição de escopo, segurança e conformidade técnica.',
		heading: 'Projeto de instalações elétricas para obras',
	},
	'/pcmso-preco': {
		primaryKeyword: 'preço de PCMSO',
		secondaryKeywords: ['custo de PCMSO', 'saúde ocupacional', 'exames ocupacionais'],
		intent: 'informacional',
		title: 'Preço de PCMSO: fatores de escopo | AJN',
		description: 'Veja quais fatores influenciam o preço de um PCMSO, como riscos, número de trabalhadores, exames e escopo de acompanhamento.',
		heading: 'Preço de PCMSO: fatores de escopo',
	},
	'/preco-pcmso': {
		primaryKeyword: 'orçamento de PCMSO',
		secondaryKeywords: ['PCMSO para empresas', 'programa de controle médico', 'saúde ocupacional'],
		intent: 'transacional',
		title: 'Orçamento de PCMSO para empresas | AJN',
		description: 'Solicite um orçamento de PCMSO para sua empresa considerando riscos ocupacionais, exames necessários e o escopo do programa.',
		heading: 'Orçamento de PCMSO para empresas',
	},
	'/plataforma-acessibilidade': {
		primaryKeyword: 'plataforma de acessibilidade',
		secondaryKeywords: ['mobilidade em edifícios', 'acessibilidade', 'solução técnica'],
		intent: 'comercial',
		title: 'Plataforma de acessibilidade: projeto e solução técnica | AJN',
		description: 'Conheça soluções de plataforma de acessibilidade para melhorar a mobilidade em edifícios, considerando o espaço e a necessidade de cada projeto.',
		heading: 'Plataforma de acessibilidade: projeto e solução técnica',
	},
	'/plataforma-acessibilidade-preco': {
		primaryKeyword: 'preço de plataforma de acessibilidade',
		secondaryKeywords: ['orçamento de plataforma', 'acessibilidade em edifícios', 'projeto técnico'],
		intent: 'transacional',
		title: 'Preço de plataforma de acessibilidade | AJN',
		description: 'Entenda o que pode influenciar o preço de uma plataforma de acessibilidade e solicite uma avaliação técnica para o seu projeto.',
		heading: 'Preço de plataforma de acessibilidade',
	},
	'/plataforma-elevatoria': {
		primaryKeyword: 'plataforma elevatória',
		secondaryKeywords: ['acesso em altura', 'equipamento de elevação', 'segurança operacional'],
		intent: 'comercial',
		title: 'Plataforma elevatória: avaliação e segurança | AJN',
		description: 'Conheça os principais usos e cuidados de segurança de uma plataforma elevatória para acesso de pessoas e ferramentas em altura.',
		heading: 'Plataforma elevatória: avaliação e segurança',
	},
	'/plataforma-elevatoria-preco': {
		primaryKeyword: 'preço de plataforma elevatória',
		secondaryKeywords: ['orçamento de plataforma elevatória', 'acesso em altura', 'segurança operacional'],
		intent: 'transacional',
		title: 'Preço de plataforma elevatória | AJN Consultoria e Engenharia',
		description: 'Veja quais características podem influenciar o preço de uma plataforma elevatória e peça orientação para definir o equipamento adequado.',
		heading: 'Preço de plataforma elevatória',
	},
	'/projeto-prevencao-combate-incendio': {
		primaryKeyword: 'projeto de prevenção contra incêndio',
		secondaryKeywords: ['segurança contra incêndio', 'PPCIP', 'regularização de edificações'],
		intent: 'informacional',
		title: 'Projeto de prevenção contra incêndio: orientação | AJN',
		description: 'Entenda os elementos de um projeto de prevenção contra incêndio e os cuidados para orientar a segurança e a regularização da edificação.',
		heading: 'Projeto de prevenção contra incêndio: orientação',
	},
} as const satisfies Record<string, KeywordMapEntry>;
