import type { BlogContentData } from '../types';
import image0 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-1dd6d711c9.jpg';
import image1 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-5c656d3809.jpg';
import image2 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-9aa82d0ea2.jpg';
import image3 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-566759720f.jpg';
import image4 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-da498c60ef.jpg';
import image5 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-f8630422f2.jpg';
import image6 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-cf7eed1251.jpg';
import image7 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-bb28a97311.jpg';
import image8 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-a1f09c1f90.jpg';
import image9 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-e4eff31c76.jpg';
import image10 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-e8de241dc8.jpg';
import image11 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-ae589c2203.jpg';
import image12 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-d214ec4317.jpg';
import image13 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-644cafb9a7.jpg';
import image14 from '../../assets/blog/blog-laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat-747301de81.jpg';

export const blogLaudoTecnicoDasCondicoesAmbientaisDeTrabalhoLtcat = {
	 slug: "laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat", path: "/blog/laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat",
	 title: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)",
	 description: "Entenda a finalidade do LTCAT, as avaliações de agentes nocivos e as situações que exigem atualização das condições ambientais registradas.",
	 heading: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)",
	 pubDate: "2025-04-15",
	 author: "Admin",
	 image: { src: image0, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" },
	 categories: ['Blog'],
	 tags: ["consultoria pcmso", "elaboracao de pgr e pcmso", "emissao ltcat", "empresa de pcmso", "laudo pgr", "laudos de saude e seguranca do trabalho", "laudos de seguranca do trabalho", "ltcat evento esocial", "ltcat renovacao", "manutencao de elevadores bh", "orcamento ltcat", "projeto de protecao contra incendio", "projeto eletrico comercial", "seguranca do trabalho ltcat", "seguranca do trabalho pcmso"],
	 gallery: [{ src: image1, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image0, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image2, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image3, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image4, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image5, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image6, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image7, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image8, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image9, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image10, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image11, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image12, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image13, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, { src: image14, alt: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }],
	 sections: [{ heading: "", paragraphs: [{ segments: ["O", { bold: true, text: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT)" }, "é um documento obrigatório para empresas que possuem funcionários expostos a agentes nocivos (químicos, físicos e biológicos). Ele tem como objetivo identificar a existência desses agentes no ambiente de trabalho e auxiliar na implementação de medidas preventivas."] }, "Algumas informações são necessárias para o preenchimento desse documento, sendo:"], lists: [{ ordered: false, items: ["A atividade exercida pelo trabalhador;", "Os agentes nocivos a que o trabalhador está exposto;", "A intensidade e concentração dos agentes nocivos;", "Dados sobre exames médicos clínicos;", "Outras informações relevantes sobre a organização do trabalho."] }], subsections: [] },
		{ heading: "Vigência do LTCAT", paragraphs: ["O LTCAT não tem prazo de validade definido. Ele deve ser atualizado sempre que houver alterações no ambiente de trabalho que possam afetar a saúde ou a integridade física dos trabalhadores. Isso garante que as informações contidas no documento estejam sempre atualizadas e condizentes com a realidade do ambiente de trabalho."], lists: [], subsections: [] },
		{ heading: "Normas que o LTCAT atende:", paragraphs: [{ segments: ["O LTCAT deve seguir as normas estabelecidas pela", { bold: true, text: "Instrução Normativa PRES/INSS nº 128/2022" }, ". Algumas das principais normas incluem:"] }, "Com isso, é possível dizer que o LTCAT é um documento essencial para a segurança e saúde dos trabalhadores expostos a agentes nocivos. Ele não apenas cumpre uma exigência legal, mas também desempenha um papel importante na prevenção de doenças ocupacionais e na garantia de um ambiente de trabalho seguro. Com base na avaliação dos riscos presentes, a empresa pode implementar medidas de controle efetivas para minimizar a exposição dos trabalhadores a esses agentes. Além disso, o LTCAT é um componente vital para a elaboração do Perfil Profissiográfico Previdenciário (PPP), que descreve as atividades desenvolvidas pelo trabalhador e as condições ambientais de trabalho a que ele foi exposto ao longo de sua vida laboral."], lists: [{ ordered: true, items: ["Identificação da empresa e do setor.", "Descrição da atividade e dos agentes prejudiciais à saúde.", "Localização das possíveis fontes geradoras dos agentes nocivos.", "Via e periodicidade de exposição ao agente prejudicial.", "Metodologia e procedimentos de avaliação dos agentes prejudiciais.", "Descrição das medidas de controle existentes.", "Conclusão do LTCAT.", "Assinatura e identificação do médico do trabalho ou engenheiro de segurança do trabalho.", "Data da realização da avaliação ambiental."] }], subsections: [] }],
} as const satisfies BlogContentData;
