export interface RouteCatalogEntry {
	path: string;
	title: string;
}

export const routeCatalog: readonly RouteCatalogEntry[] = [
	{ path: "/", title: "Serviços de Engenharia de Segurança do Trabalho - AJN Consultoria e Engenharia" },
	{ path: "/empresa-elevador-belo-horizonte", title: "Empresa de elevador belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-industrial-preco", title: "Projeto eletrico industrial preço - AJN Consultoria e Engenharia" },
	{ path: "/consultoria-da-qualidade", title: "Consultoria da qualidade - AJN Consultoria e Engenharia" },
	{ path: "/blog/laudo-tecnico-das-condicoes-ambientais-de-trabalho-ltcat", title: "Laudo Técnico das Condições Ambientais de Trabalho (LTCAT) - AJN Consultoria e Engenharia" },
	{ path: "/elaboracao-pgr-pcmso", title: "Elaboração de pgr e pcmso - AJN Consultoria e Engenharia" },
	{ path: "/pericias-insalubridade-periculosidade", title: "Perícias de insalubridade e periculosidade - AJN Consultoria e Engenharia" },
	{ path: "/empresa-que-elabora-pgr", title: "Empresa que elabora pgr - AJN Consultoria e Engenharia" },
	{ path: "/projeto-instalacao-eletrica-residencial", title: "Projeto de instalação elétrica residencial - AJN Consultoria e Engenharia" },
	{ path: "/projeto-seguranca-incendio", title: "Projeto de segurança contra incêndio - AJN Consultoria e Engenharia" },
	{ path: "/instalacao-predial-eletrica", title: "Instalação predial elétrica - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-residencial-belo-horizonte", title: "Projeto elétrico residencial belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/empresa-ltcat", title: "Empresa ltcat - AJN Consultoria e Engenharia" },
	{ path: "/inspecoes-seguranca-do-trabalho", title: "Inspeções de segurança do trabalho - AJN Consultoria e Engenharia" },
	{ path: "/pcmso-preco", title: "Pcmso preço - AJN Consultoria e Engenharia" },
	{ path: "/laudos-seguranca-do-trabalho", title: "Laudos de segurança do trabalho - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-industrial-belo-horizonte", title: "Projeto elétrico industrial belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-acessibilidade", title: "Plataforma de acessibilidade - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-residencial-orcamento", title: "Projeto eletrico residencial orçamento - AJN Consultoria e Engenharia" },
	{ path: "/laudo-ltcat-insalubridade", title: "Laudo ltcat insalubridade - AJN Consultoria e Engenharia" },
	{ path: "/empresa-escada-rolante", title: "Empresa de escada rolante - AJN Consultoria e Engenharia" },
	{ path: "/projeto-sistema-combate-incendio", title: "Projeto de sistema de combate a incêndio - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-papel-fundamental-na-seguranca-do-trabalho-e-no-bem-estar-dos-colaboradores", title: "LTCAT: Papel Fundamental na Segurança do Trabalho e no Bem-Estar dos Colaboradores - AJN Consultoria e Engenharia" },
	{ path: "/projeto-combate-incendio-preco", title: "Projeto de combate a incêndio preço - AJN Consultoria e Engenharia" },
	{ path: "/projeto-prevencao-incendio-panico", title: "Projeto de prevenção contra incêndio e pânico - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-residencial-completo", title: "Projeto elétrico residencial completo - AJN Consultoria e Engenharia" },
	{ path: "/analise-projetos-eletricos-bh", title: "Análise de projetos elétricos em bh - AJN Consultoria e Engenharia" },
	{ path: "/blog/orcamento-eficiente-para-ltcat-passos-essenciais-para-garantir-a-seguranca-no-trabalho", title: "Orçamento Eficiente para LTCAT: Passos Essenciais para Garantir a Segurança no Trabalho - AJN Consultoria e Engenharia" },
	{ path: "/empresa-projeto-eletrico-bh", title: "Empresa de projeto elétrico bh - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-comercial", title: "Projeto elétrico comercial - AJN Consultoria e Engenharia" },
	{ path: "/empresa-que-faz-ltcat", title: "Empresa que faz ltcat - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-e-seguranca-do-trabalho-como-garantir-a-protecao-eficaz-da-sua-equipe", title: "LTCAT e Segurança do Trabalho: Como Garantir a Proteção Eficaz da Sua Equipe - AJN Consultoria e Engenharia" },
	{ path: "/empresas-elevadores-bh", title: "Empresas de elevadores em bh - AJN Consultoria e Engenharia" },
	{ path: "/contato", title: "Contato - AJN Consultoria e Engenharia" },
	{ path: "/projeto-sistema-incendio", title: "Projeto de sistema de incêndio - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-e-seguranca-do-trabalho-como-proteger-sua-empresa-com-eficiencia", title: "LTCAT e Segurança do Trabalho: Como Proteger Sua Empresa com Eficiência - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico", title: "Projeto elétrico - AJN Consultoria e Engenharia" },
	{ path: "/combate-incendio-belo-horizonte", title: "Combate a incêndio belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/projetos-engenharia-eletrica", title: "Projetos de engenharia elétrica - AJN Consultoria e Engenharia" },
	{ path: "/instalacoes-eletricas-projeto", title: "Instalações elétricas projeto - AJN Consultoria e Engenharia" },
	{ path: "/escada-rolante", title: "Escada rolante - AJN Consultoria e Engenharia" },
	{ path: "/blog/o-fim-do-ppra-e-a-chegada-do-pgr-o-que-mudou", title: "O Fim do PPRA e a chegada do PGR: o que mudou? - AJN Consultoria e Engenharia" },
	{ path: "/projetos-eletricos-orcamento", title: "Projetos eletricos orçamento - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-guia-essencial-para-garantir-a-seguranca-no-ambiente-de-trabalho", title: "LTCAT: Guia Essencial para Garantir a Segurança no Ambiente de Trabalho - AJN Consultoria e Engenharia" },
	{ path: "/blog/ppp-facil-o-ue-e-como-consultar-e-sua-importancia", title: "PPP Fácil: O Ǫue é, Como Consultar e Sua Importância - AJN Consultoria e Engenharia" },
	{ path: "/orcamento-projeto-combate-incendio", title: "Orçamento projeto de combate a incêndio - AJN Consultoria e Engenharia" },
	{ path: "/escada-rolante-belo-horizonte", title: "Escada rolante belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/valor-projeto-incendio", title: "Valor projeto de incêndio - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-elevatoria", title: "Plataforma elevatória - AJN Consultoria e Engenharia" },
	{ path: "/ltcat-evento-esocial", title: "Ltcat evento esocial - AJN Consultoria e Engenharia" },
	{ path: "/projeto-prevencao-combate-incendio", title: "Projeto de prevenção e combate a incêndio - AJN Consultoria e Engenharia" },
	{ path: "/elaboracao-do-pgr-pcmso", title: "Elaboração do pgr e pcmso - AJN Consultoria e Engenharia" },
	{ path: "/projetos-instalacoes-eletricas-prediais", title: "Projetos de instalações elétricas prediais - AJN Consultoria e Engenharia" },
	{ path: "/ltcat-preco", title: "Ltcat preço - AJN Consultoria e Engenharia" },
	{ path: "/blog/seguranca-do-trabalho-e-pcmso-gestao-da-saude-ocupacional", title: "Segurança do Trabalho e PCMSO: Gestão da Saúde Ocupacional - AJN Consultoria e Engenharia" },
	{ path: "/empresa-combate-incendio-bh", title: "Empresa de combate a incêndio em bh - AJN Consultoria e Engenharia" },
	{ path: "/servicos/gestao-ambiental", title: "Gestão Ambiental - AJN Consultoria e Engenharia" },
	{ path: "/blog/a-importancia-do-ltcat-para-a-seguranca-do-trabalho-e-a-protecao-do-ambiente-profissional", title: "A Importância do LTCAT para a Segurança do Trabalho e a Proteção do Ambiente Profissional - AJN Consultoria e Engenharia" },
	{ path: "/servicos/projetos-de-combate-a-incendio-e-panico-ppcip", title: "Projetos de Combate a Incêndio e Pânico - PPCIP - AJN Consultoria e Engenharia" },
	{ path: "/servicos/projetos-eletricos-residenciais-comerciais-e-prediais-com-foco-em-qualidade-prazo-e-economia", title: "Projetos Elétricos Residenciais, Comerciais e Prediais com Foco em Qualidade, Prazo e Economia - AJN Consultoria e Engenharia" },
	{ path: "/consultoria-seguranca-saude-no-trabalho", title: "Consultoria segurança e saude no trabalho - AJN Consultoria e Engenharia" },
	{ path: "/servico-projeto-eletrico", title: "Serviço de projeto elétrico - AJN Consultoria e Engenharia" },
	{ path: "/servicos/assessoria-e-consultoria-em-saude-ocupacional", title: "Assessoria e consultoria em saúde ocupacional - AJN Consultoria e Engenharia" },
	{ path: "/orcamento-pgr", title: "Orçamento pgr - AJN Consultoria e Engenharia" },
	{ path: "/blog/laudo-de-gerenciamento-de-riscos-essencial-para-garantir-a-seguranca-no-ambiente-de-trabalho", title: "Laudo de Gerenciamento de Riscos: Essencial para Garantir a Segurança no Ambiente de Trabalho - AJN Consultoria e Engenharia" },
	{ path: "/pcmso-programa-controle-medico-saude-ocupacional", title: "Pcmso programa de controle médico de saúde ocupacional - AJN Consultoria e Engenharia" },
	{ path: "/ltcat-renovacao", title: "Ltcat renovação - AJN Consultoria e Engenharia" },
	{ path: "/ltcat-orcamento", title: "Ltcat orçamento - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-na-seguranca-do-trabalho-fortaleca-a-protecao-dos-seus-funcionarios-eficazmente", title: "LTCAT na Segurança do Trabalho: Fortaleça a Proteção dos Seus Funcionários Eficazmente - AJN Consultoria e Engenharia" },
	{ path: "/empresas-manutencao-elevadores-bh", title: "Empresas de manutenção de elevadores em bh - AJN Consultoria e Engenharia" },
	{ path: "/emissao-laudos", title: "Emissão de laudos - AJN Consultoria e Engenharia" },
	{ path: "/orcamento-projeto-eletrico", title: "Orçamento de projeto elétrico - AJN Consultoria e Engenharia" },
	{ path: "/empresa-elevador", title: "Empresa de elevador - AJN Consultoria e Engenharia" },
	{ path: "/blog/seguranca-do-trabalho-e-ltcat-conformidade-e-protecao-previdenciaria", title: "Segurança do Trabalho e LTCAT: Conformidade e Proteção Previdenciária - AJN Consultoria e Engenharia" },
	{ path: "/empresa-combate-incendio", title: "Empresa de combate a incêndio - AJN Consultoria e Engenharia" },
	{ path: "/projeto-combate-incendio-panico", title: "Projeto de combate a incêndio e pânico - AJN Consultoria e Engenharia" },
	{ path: "/empresa-que-faz-pgr", title: "Empresa que faz pgr - AJN Consultoria e Engenharia" },
	{ path: "/servicos", title: "Serviços - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-bh", title: "Projeto elétrico bh - AJN Consultoria e Engenharia" },
	{ path: "/seguranca-do-trabalho-ltcat", title: "Segurança do trabalho ltcat - AJN Consultoria e Engenharia" },
	{ path: "/orcamento-ltcat", title: "Orçamento ltcat - AJN Consultoria e Engenharia" },
	{ path: "/consultoria-pcmso", title: "Consultoria pcmso - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-industrial", title: "Projeto elétrico industrial - AJN Consultoria e Engenharia" },
	{ path: "/elevacao-vertical", title: "Elevação vertical - AJN Consultoria e Engenharia" },
	{ path: "/projeto-incendio", title: "Projeto contra incêndio - AJN Consultoria e Engenharia" },
	{ path: "/consultoria-seguranca-do-trabalho", title: "Consultoria segurança do trabalho - AJN Consultoria e Engenharia" },
	{ path: "/elaboracao-projeto-combate-incendio", title: "Elaboração de projeto de combate a incêndio - AJN Consultoria e Engenharia" },
	{ path: "/projetos-eletricos-prediais", title: "Projetos elétricos prediais - AJN Consultoria e Engenharia" },
	{ path: "/servicos/gestao-da-qualidade", title: "Gestão da Qualidade - AJN Consultoria e Engenharia" },
	{ path: "/preco-projetos-eletricos", title: "Preço de projetos eletricos - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-preco", title: "Projeto elétrico preço - AJN Consultoria e Engenharia" },
	{ path: "/projeto-seguranca-incendio-panico", title: "Projeto de segurança contra incêndio e pânico - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-belo-horizonte", title: "Projeto elétrico belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/valor-elaboracao-pgr", title: "Valor para elaboração de pgr - AJN Consultoria e Engenharia" },
	{ path: "/projeto-protecao-incendio", title: "Projeto de proteção contra incêndio - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-elevatoria-belo-horizonte", title: "Plataforma elevatória belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-guia-essencial-para-garantir-seguranca-do-trabalho-eficaz", title: "LTCAT: Guia Essencial para Garantir Segurança do Trabalho Eficaz - AJN Consultoria e Engenharia" },
	{ path: "/elaboracao-pcmso", title: "Elaboração pcmso - AJN Consultoria e Engenharia" },
	{ path: "/empresa-que-faz-pcmso", title: "Empresa que faz pcmso - AJN Consultoria e Engenharia" },
	{ path: "/laudos-seguranca-do-trabalho-esocial", title: "Laudos segurança do trabalho esocial - AJN Consultoria e Engenharia" },
	{ path: "/projeto-protecao-incendio-panico", title: "Projeto de proteção contra incêndio e pânico - AJN Consultoria e Engenharia" },
	{ path: "/seguranca-do-trabalho-pcmso", title: "Segurança do trabalho pcmso - AJN Consultoria e Engenharia" },
	{ path: "/empresa-projeto-eletrico", title: "Empresa de projeto elétrico - AJN Consultoria e Engenharia" },
	{ path: "/elevador-bh", title: "Elevador bh - AJN Consultoria e Engenharia" },
	{ path: "/manutencao-elevadores-belo-horizonte", title: "Manutenção de elevadores em belo horizonte - AJN Consultoria e Engenharia" },
	{ path: "/blog/um-pouco-sobre-nos", title: "Um pouco sobre nós - AJN Consultoria e Engenharia" },
	{ path: "/empresa-pcmso", title: "Empresa de pcmso - AJN Consultoria e Engenharia" },
	{ path: "/servicos/pericias-em-periculosidade-e-insalubridade", title: "Perícias em Periculosidade e Insalubridade - AJN Consultoria e Engenharia" },
	{ path: "/projeto-eletrico-residencial", title: "Projeto elétrico residencial - AJN Consultoria e Engenharia" },
	{ path: "/inspecao-seguranca-saude-no-ambiente-trabalho", title: "Inspeção em segurança e saúde no ambiente de trabalho - AJN Consultoria e Engenharia" },
	{ path: "/blog", title: "Blog - AJN Consultoria e Engenharia" },
	{ path: "/servicos-pcmso", title: "Serviços de pcmso - AJN Consultoria e Engenharia" },
	{ path: "/blog/perfil-profissiografico-previdenciario-ppp", title: "Perfil Profissiográfico Previdenciário (PPP) - AJN Consultoria e Engenharia" },
	{ path: "/elaboracao-pgr", title: "Elaboração de pgr - AJN Consultoria e Engenharia" },
	{ path: "/blog/nr-35-trabalho-em-altura-e-seguranca", title: "NR-35:Trabalho em Altura e Segurança - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-acessibilidade-bh", title: "Plataforma de acessibilidade bh - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-na-seguranca-do-trabalho-garantindo-protecao-e-reducao-de-riscos-para-sua-equipe", title: "LTCAT na Segurança do Trabalho: Garantindo Proteção e Redução de Riscos para sua Equipe - AJN Consultoria e Engenharia" },
	{ path: "/manutencao-elevadores-bh", title: "Manutenção de elevadores bh - AJN Consultoria e Engenharia" },
	{ path: "/empresa-plataforma-elevatoria", title: "Empresa de plataforma elevatória - AJN Consultoria e Engenharia" },
	{ path: "/valor-projeto-combate-incendio", title: "Valor de projeto de combate a incêndio - AJN Consultoria e Engenharia" },
	{ path: "/projeto-deteccao-incendio", title: "Projeto de detecção de incêndio - AJN Consultoria e Engenharia" },
	{ path: "/laudos-saude-seguranca-do-trabalho", title: "Laudos de saude e segurança do trabalho - AJN Consultoria e Engenharia" },
	{ path: "/orcamento-pcmso", title: "Orçamento pcmso - AJN Consultoria e Engenharia" },
	{ path: "/servicos/gestao-do-e-social", title: "Gestão do E-Social - AJN Consultoria e Engenharia" },
	{ path: "/mobilizacao-pessoal-equipamentos", title: "Mobilização de pessoal e equipamentos - AJN Consultoria e Engenharia" },
	{ path: "/mapa-site", title: "Mapa do site - AJN Consultoria e Engenharia" },
	{ path: "/sistemas-incendio-bh", title: "Sistemas contra incêndio bh - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-elevatoria-preco", title: "Plataforma elevatória preço - AJN Consultoria e Engenharia" },
	{ path: "/sobre-nos", title: "Sobre Nós - AJN Consultoria e Engenharia" },
	{ path: "/blog/ltcat-essencial-para-a-seguranca-do-trabalho-e-protecao-da-sua-equipe", title: "LTCAT: Essencial para a Segurança do Trabalho e Proteção da Sua Equipe - AJN Consultoria e Engenharia" },
	{ path: "/servicos/treinamento-de-nrs", title: "Treinamento de NRs - AJN Consultoria e Engenharia" },
	{ path: "/valor-fazer-ltcat", title: "Valor para fazer ltcat - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-elevatoria-bh", title: "Plataforma elevatória bh - AJN Consultoria e Engenharia" },
	{ path: "/blog/elaboracao-de-pgr-e-pcmso-conformidade-e-seguranca-no-trabalho", title: "Elaboração de PGR e PCMSO: Conformidade e Segurança no Trabalho - AJN Consultoria e Engenharia" },
	{ path: "/preco-pcmso", title: "Preço de pcmso - AJN Consultoria e Engenharia" },
	{ path: "/projeto-instalacoes-eletricas", title: "Projeto de instalações elétricas - AJN Consultoria e Engenharia" },
	{ path: "/servicos/regularizacao-de-imoveis-junto-ao-corpo-de-bombeiros", title: "Regularização de imóveis junto ao corpo de bombeiros - AJN Consultoria e Engenharia" },
	{ path: "/laudo-pgr", title: "Laudo pgr - AJN Consultoria e Engenharia" },
	{ path: "/laudos-sst", title: "Laudos de sst - AJN Consultoria e Engenharia" },
	{ path: "/servicos/pcmso-e-asos", title: "PCMSO e ASOs - AJN Consultoria e Engenharia" },
	{ path: "/plataforma-acessibilidade-preco", title: "Plataforma de acessibilidade preço - AJN Consultoria e Engenharia" },
	{ path: "/emissao-ltcat", title: "Emissão ltcat - AJN Consultoria e Engenharia" },
	{ path: "/escada-rolante-bh", title: "Escada rolante bh - AJN Consultoria e Engenharia" },
	{ path: "/projetos-spda", title: "Projetos de SPDA - AJN Consultoria e Engenharia" },
	{ path: "/projetos-cabeamento-estruturado", title: "Projetos de cabeamento estruturado - AJN Consultoria e Engenharia" },
] as const;

