export const serviceIndexItems = [
  { title: 'Assessoria e consultoria em saúde ocupacional', description: 'Identificação de perigos, avaliação de riscos e orientação sobre medidas de prevenção nas atividades da empresa.', href: '/servicos/assessoria-e-consultoria-em-saude-ocupacional', image: '/images/content/services/assessoria-e-consultoria-em-saude-ocupacional.webp' },
  { title: 'Gestão Ambiental', description: 'Apoio à organização de resíduos e aos procedimentos de gestão ambiental conforme as necessidades da operação.', href: '/servicos/gestao-ambiental', image: '/images/content/services/gestao-ambiental.webp' },
  { title: 'Gestão da Qualidade', description: 'Planejamento, documentação e acompanhamento de requisitos de qualidade em obras e serviços contratados.', href: '/servicos/gestao-da-qualidade', image: '/images/content/services/gestao-da-qualidade.webp' },
  { title: 'Gestão do E-Social', description: 'Organização das informações de SST e apoio aos eventos ocupacionais enviados ao eSocial.', href: '/servicos/gestao-do-e-social', image: '/images/content/services/gestao-do-e-social.webp' },
  { title: 'PCMSO e ASOs', description: 'Acompanhamento documental do PCMSO e organização dos exames ocupacionais e atestados de saúde ocupacional.', href: '/servicos/pcmso-e-asos', image: '/images/content/services/pcmso-e-asos.jpg' },
  { title: 'Perícias em Periculosidade e Insalubridade', description: 'Avaliações técnicas das condições de exposição para subsidiar perícias e laudos trabalhistas.', href: '/servicos/pericias-em-periculosidade-e-insalubridade', image: '/images/content/services/pericias-em-periculosidade-e-insalubridade.webp' },
  { title: 'Projetos de Combate a Incêndio e Pânico - PPCIP', description: 'Projetos e documentação de prevenção e combate a incêndio conforme o tipo de edificação e as exigências aplicáveis.', href: '/servicos/projetos-de-combate-a-incendio-e-panico-ppcip', image: '/images/content/services/projetos-de-combate-a-incendio-e-panico-ppcip.webp' },
  { title: 'Projetos Elétricos Residenciais, Comerciais e Prediais com Foco em Qualidade, Prazo e Economia', description: 'Projetos elétricos para diferentes tipos de edificação, com escopo e documentação técnica definidos para cada demanda.', href: '/projetos-eletricos-prediais', image: '/images/featured/orcamento-projeto-eletrico-01.webp' },
  { title: 'Regularização de imóveis junto ao corpo de bombeiros', description: 'Análise da situação da edificação e elaboração dos projetos e documentos de prevenção contra incêndio necessários.', href: '/servicos/regularizacao-de-imoveis-junto-ao-corpo-de-bombeiros', image: '/images/content/services/regularizacao-de-imoveis-junto-ao-corpo-de-bombeiros.webp' },
  { title: 'Treinamento de NRs', description: 'Treinamentos relacionados às Normas Regulamentadoras, conforme a atividade, os riscos e os requisitos aplicáveis.', href: '/servicos/treinamento-de-nrs', image: '/images/content/services/treinamento-de-nrs.webp' },
] as const;
