export const serviceIndexItems = [
	{ title: 'Assessoria e consultoria em saúde ocupacional', description: 'Assessoria e Consultoria: Oferecemos suporte técnico e estratégico para identificar, avaliar e controlar riscos ocupacionais. Isso inclui a elaboração de...', href: '/servicos/assessoria-e-consultoria-em-saude-ocupacional' },
	{ title: 'Gestão Ambiental', description: '1 - Gestão ambiental - Segregação, armazenamento e destinação correta dos resíduos. Segregação de Resíduos: A segregação envolve a separação dos...', href: '/servicos/gestao-ambiental' },
	{ title: 'Gestão da Qualidade', description: '1 - Plano de Qualidade de Obras: Este documento detalha os critérios de qualidade que devem ser seguidos durante a...', href: '/servicos/gestao-da-qualidade' },
	{ title: 'Gestão do E-Social', description: '1 - Serviços de Gestão do eSocial para Empresas A gestão do eSocial é essencial para garantir que as empresas cumpram...', href: '/servicos/gestao-do-e-social' },
	{ title: 'PCMSO e ASOs', description: '1 - Manter Atualizado o PCMSO Conforme Riscos do PGR: O PCMSO deve ser constantemente revisado e atualizado com base...', href: '/servicos/pcmso-e-asos' },
	{ title: 'Perícias em Periculosidade e Insalubridade', description: '1 - Perícia de Insalubridade: Avalia se o ambiente de trabalho expõe os trabalhadores a agentes nocivos à saúde, como...', href: '/servicos/pericias-em-periculosidade-e-insalubridade' },
	{ title: 'Projetos de Combate a Incêndio e Pânico - PPCIP', description: '1 - Elaboração de projetos conforme normativas (ITs - Instruções técnicas): - Para atender às necessidades específicas de segurança contra...', href: '/servicos/projetos-de-combate-a-incendio-e-panico-ppcip' },
	{ title: 'Projetos Elétricos Residenciais, Comerciais e Prediais com Foco em Qualidade, Prazo e Economia', description: 'A atuação da AJN Consultoria e Engenharia abrange serviços especializados na elaboração de projetos elétricos para empreendimentos residenciais de alto...', href: '/servicos/projetos-eletricos-residenciais-comerciais-e-prediais-com-foco-em-qualidade-prazo-e-economia' },
	{ title: 'Regularização de imóveis junto ao corpo de bombeiros', description: '1 - Elaboração de projetos conforme normativas para atender às necessidades específicas de segurança contra incêndios de edificações comerciais, residenciais...', href: '/servicos/regularizacao-de-imoveis-junto-ao-corpo-de-bombeiros' },
	{ title: 'Treinamento de NRs', description: '1 - Treinamento de NR 01 - DISPOSIÇÕES GERAIS E GERENCIAMENTO DE RISCOS OCUPACIONAIS 2 - Treinamento de NR 06 -...', href: '/servicos/treinamento-de-nrs' },
] as const;
